server:
  port: 8080

spring:
  application:
    name: Chatly

  datasource:
    url: jdbc:h2:mem:chatlydb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

jwt:
  secret: sdfgio8uy765456789okjbvcfdre5678oikjnbvcfdr5678uijknbvcftr6yuijnbvcfd
  expiration: 3600000   # 1 hour in ms

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
